// Generated by CoffeeScript 1.6.2
(function() {
  if (!jsedn) {
    jsedn = require("jsedn");
  }

  module.exports = {
    _kwParts: function(kw) {
      var parts;

      parts = kw.replace(/\:/g, "").split("/");
      switch (parts.length) {
        case 1:
          return {
            namespace: null,
            value: parts[0]
          };
        case 2:
          return {
            namespace: parts[0],
            value: parts[1]
          };
        default:
          throw new Error("keyword invalid. expects x/y, a.b.c/d or just x");
      }
    },
    _kwUrl: function(kw) {
      var namespace, value, _ref;

      _ref = this._kwParts(kw), namespace = _ref.namespace, value = _ref.value;
      return "http://" + (namespace || "www") + ".edn.io/:" + value;
    },
    get: function(key) {
      return $.ajax({
        type: "GET",
        url: this._kwUrl(key),
        dataFilter: function(data) {
          return jsedn.parse(data);
        }
      });
    },
    set: function(key, value) {
      return $.ajax({
        type: "POST",
        url: this._kwUrl(key),
        data: value
      });
    }
  };

}).call(this);
